#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Utilities to build AT3D grid-data CSV files.

Design goals
------------
1) Keep AT3D CSV header compatibility.
2) Support both retrieval-1D style and LES-style sources.
3) Allow optional multi-mode/surface/per-grid-refractive-index columns.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Mapping, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import xarray as xr


BASE_COLUMNS = ["x", "y", "z", "cv", "lat", "lon"]
SURFACE_COLUMNS = [
    "surface_model",  # lambertian | wave_fresnel | diner | ocean_unpolarized | rpv_unpolarized
    "surface_albedo",
    "surface_wind_speed",
    "surface_pigmentation",
    "surface_refractive_index_real",
    "surface_refractive_index_imag",
    "surface_parameter_1",
    "surface_parameter_2",
    "surface_parameter_3",
]


@dataclass
class ExtendedGridOptions:
    mode_count: int = 2
    include_surface: bool = True
    include_per_grid_refractive_index: bool = True


@dataclass
class GridGeometry:
    nx: int
    ny: int
    nz: int
    dx_km: float
    dy_km: float
    z_levels_km: Sequence[float]


def _mode_columns(mode_count: int) -> List[str]:
    cols: List[str] = []
    for mode in range(1, mode_count + 1):
        cols.extend([
            f"mode{mode}_fraction",
            f"mode{mode}_reff",
            f"mode{mode}_veff",
            f"mode{mode}_mr",
            f"mode{mode}_mi",
        ])
    return cols


def _ensure_columns(df: pd.DataFrame, required: Sequence[str]) -> None:
    missing = [name for name in required if name not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")


def _broadcast_2d_to_3d(arr2d: np.ndarray, nz: int) -> np.ndarray:
    return np.repeat(arr2d[:, :, None], nz, axis=2)


def _coarse_mean_2d(arr: np.ndarray, cy: int, cx: int) -> np.ndarray:
    ny, nx = arr.shape
    ny_c = ny // cy
    nx_c = nx // cx
    arr_t = arr[: ny_c * cy, : nx_c * cx]
    return arr_t.reshape(ny_c, cy, nx_c, cx).mean(axis=(1, 3))


def _coarse_mean_3d(arr: np.ndarray, cz: int, cy: int, cx: int) -> np.ndarray:
    nz, ny, nx = arr.shape
    nz_c = nz // cz
    ny_c = ny // cy
    nx_c = nx // cx
    arr_t = arr[: nz_c * cz, : ny_c * cy, : nx_c * cx]
    return arr_t.reshape(nz_c, cz, ny_c, cy, nx_c, cx).mean(axis=(1, 3, 5))


def _flatten_xyz(arr3d_yxz: np.ndarray) -> np.ndarray:
    # Input order: (y, x, z), matching load_from_csv output convention.
    # Output order follows x/y/z index columns generated by meshgrid(indexing='xy').
    return np.asarray(arr3d_yxz).reshape(-1)




def _to_2d_field(arr: np.ndarray, ny: int, nx: int, name: str, wavelength_index: int = 0) -> np.ndarray:
    """Normalize array to (ny, nx).

    Supports:
    - 2D field: (ny, nx)
    - 3D spectral field: one axis is wavelength/band, e.g. (nband, ny, nx)
      or (ny, nx, nband). `wavelength_index` is selected.
    """
    arr = np.asarray(arr, dtype=float)
    if arr.ndim == 2:
        if arr.shape != (ny, nx):
            raise ValueError(f"{name} shape {arr.shape} != expected {(ny, nx)}")
        return arr

    if arr.ndim == 3:
        candidate_axes = []
        for axis in range(3):
            s = arr.shape
            other = tuple(s[i] for i in range(3) if i != axis)
            if other == (ny, nx):
                candidate_axes.append(axis)
        if not candidate_axes:
            raise ValueError(
                f"{name} has 3 dims {arr.shape} but cannot find spectral axis for target {(ny, nx)}"
            )
        spec_axis = candidate_axes[0]
        nband = arr.shape[spec_axis]
        if wavelength_index < 0 or wavelength_index >= nband:
            raise IndexError(f"wavelength_index={wavelength_index} out of range [0, {nband-1}] for {name}")
        arr2d = np.take(arr, indices=wavelength_index, axis=spec_axis)
        if arr2d.shape != (ny, nx):
            raise ValueError(f"{name} selected slice shape {arr2d.shape} != expected {(ny, nx)}")
        return arr2d

    raise ValueError(f"{name} must be 2D or 3D, got shape {arr.shape}")

def generate_latlon(lat0: float, lon0: float, dx_m: float, dy_m: float, ny: int, nx: int) -> Tuple[np.ndarray, np.ndarray]:
    """Generate regular-grid lat/lon from origin + spacing (LES fallback helper)."""
    km_per_deg_lat = 111.32
    km_per_deg_lon = 111.32 * np.cos(np.deg2rad(lat0))
    lat_1d = lat0 + (np.arange(ny) * dy_m / 1000.0) / km_per_deg_lat
    lon_1d = lon0 + (np.arange(nx) * dx_m / 1000.0) / km_per_deg_lon
    return np.meshgrid(lat_1d, lon_1d, indexing='ij')




def _z_layer_thickness_km(z_levels_km: Sequence[float]) -> np.ndarray:
    z = np.asarray(z_levels_km, dtype=float)
    if z.ndim != 1 or z.size < 2:
        raise ValueError("z_levels_km must contain at least 2 levels")
    z_edge = np.concatenate(([z[0] - (z[1]-z[0])/2], 0.5*(z[:-1] + z[1:]), [z[-1] + (z[-1]-z[-2])/2]))
    return np.diff(z_edge)


def _column_to_mass_density_profile(cv_column_um: np.ndarray,
                                    z_levels_km: Sequence[float],
                                    h_km: np.ndarray,
                                    sigma_km: np.ndarray,
                                    particle_density_g_cm3: float) -> np.ndarray:
    """Convert column-integrated Cv_total [um] to 3D mass density [g/m^3]."""
    z = np.asarray(z_levels_km, dtype=float)
    dz_km = _z_layer_thickness_km(z)

    h = np.asarray(h_km, dtype=float)
    sigma = np.asarray(sigma_km, dtype=float)
    sigma = np.where(np.isfinite(sigma) & (sigma > 1e-6), sigma, 0.5)

    # Gaussian shape in z for each (y,x)
    w = np.exp(-((z[None, None, :] - h[:, :, None]) ** 2) / (2.0 * sigma[:, :, None] ** 2))
    norm = np.sum(w * dz_km[None, None, :], axis=2, keepdims=True)
    norm = np.where(norm > 0, norm, 1.0)
    w = w / norm

    # MATLAB-equivalent: mass_density_z = rho_p[g/cm^3] * Cv_total[um] * w * 1e-3  [g/m^3]
    mass_density = float(particle_density_g_cm3) * cv_column_um[:, :, None] * w * 1e-3
    return mass_density





def _first_existing_var(ds: xr.Dataset, candidates: Sequence[str]) -> Optional[str]:
    for name in candidates:
        if name and name in ds:
            return name
    return None

def _estimate_dxdy_from_latlon(lat2d: np.ndarray, lon2d: np.ndarray) -> Tuple[float, float]:
    """Estimate NEU grid spacing from geodetic grid.

    Returns
    -------
    dx_km : spacing along x (North direction)
    dy_km : spacing along y (East direction)
    """
    lat = np.asarray(lat2d, dtype=float)
    lon = np.asarray(lon2d, dtype=float)

    valid = (
        np.isfinite(lat)
        & np.isfinite(lon)
        & (np.abs(lat) > 1e-12)
        & (np.abs(lon) > 1e-12)
        & (np.abs(lat) <= 90.0)
        & (np.abs(lon) <= 180.0)
    )

    # North-direction neighbors (row-to-row): map to x in NEU.
    valid_n = valid[1:, :] & valid[:-1, :]
    dlat_n = lat[1:, :] - lat[:-1, :]
    dlon_n = lon[1:, :] - lon[:-1, :]
    lat_mid_n = 0.5 * (lat[1:, :] + lat[:-1, :])
    dn_km = np.sqrt((dlat_n * 111.32) ** 2 + (dlon_n * 111.32 * np.cos(np.deg2rad(lat_mid_n))) ** 2)
    dn_km = dn_km[valid_n]

    # East-direction neighbors (col-to-col): map to y in NEU.
    valid_e = valid[:, 1:] & valid[:, :-1]
    dlat_e = lat[:, 1:] - lat[:, :-1]
    dlon_e = lon[:, 1:] - lon[:, :-1]
    lat_mid_e = 0.5 * (lat[:, 1:] + lat[:, :-1])
    de_km = np.sqrt((dlat_e * 111.32) ** 2 + (dlon_e * 111.32 * np.cos(np.deg2rad(lat_mid_e))) ** 2)
    de_km = de_km[valid_e]

    def _robust_spacing(vals: np.ndarray) -> float:
        vals = np.asarray(vals, dtype=float)
        vals = vals[np.isfinite(vals) & (vals > 0.0)]
        if vals.size == 0:
            return np.nan
        if vals.size > 10:
            lo, hi = np.nanpercentile(vals, [5, 95])
            vals = vals[(vals >= lo) & (vals <= hi)]
        if vals.size > 20:
            p25, p50 = np.nanpercentile(vals, [25, 50])
            # If mixed scales exist (e.g., valid cell size + sparse large jumps),
            # prefer the finer-scale cluster for grid spacing.
            if np.isfinite(p25) and np.isfinite(p50) and p25 > 0 and (p50 / p25) > 1.8:
                vals = vals[vals <= (1.5 * p25)]
        return float(np.nanmedian(vals)) if vals.size else np.nan

    dx_km = _robust_spacing(dn_km)
    dy_km = _robust_spacing(de_km)
    if not np.isfinite(dx_km) or dx_km <= 0:
        dx_km = 0.25
    if not np.isfinite(dy_km) or dy_km <= 0:
        dy_km = 0.25
    return dx_km, dy_km

def validate_extended_grid_data(df: pd.DataFrame, options: ExtendedGridOptions) -> None:
    required = list(BASE_COLUMNS)
    required.extend(_mode_columns(options.mode_count))
    _ensure_columns(df, required)

    # Backward compatibility: either legacy scalar columns exist,
    # or mode1 columns must be present (preferred extended schema).
    has_scalar = ("reff" in df.columns) and ("veff" in df.columns)
    has_mode1 = ("mode1_reff" in df.columns) and ("mode1_veff" in df.columns)
    if not (has_scalar or has_mode1):
        raise ValueError("Need either ('reff','veff') or ('mode1_reff','mode1_veff') columns")

    if options.include_surface:
        if "surface_model" in df.columns:
            valid_models = {
                "lambertian", "wave_fresnel", "diner", "ocean_unpolarized", "rpv_unpolarized"
            }
            bad = sorted(set(df["surface_model"].dropna().astype(str)) - valid_models)
            if bad:
                raise ValueError(f"Unsupported surface_model values: {bad}")

    fractions = [f"mode{m}_fraction" for m in range(1, options.mode_count + 1)]
    frac_sum = df[fractions].sum(axis=1)
    finite = np.isfinite(frac_sum)
    if np.any(np.abs(frac_sum[finite] - 1.0) > 1e-3):
        raise ValueError("mode fractions must sum to 1 (±1e-3) for finite rows")


def build_extended_grid_dataframe(base_columns: Mapping[str, np.ndarray], options: Optional[ExtendedGridOptions] = None) -> pd.DataFrame:
    options = options or ExtendedGridOptions()
    records = {k: np.asarray(v).reshape(-1) for k, v in base_columns.items()}
    df = pd.DataFrame(records)
    validate_extended_grid_data(df, options)
    return df


def write_extended_grid_csv(
    output_path: str | Path,
    df: pd.DataFrame,
    geometry: GridGeometry,
    options: Optional[ExtendedGridOptions] = None,
    extra_metadata: Optional[Mapping[str, str]] = None,
) -> Path:
    options = options or ExtendedGridOptions()
    validate_extended_grid_data(df, options)

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    if len(geometry.z_levels_km) != geometry.nz:
        raise ValueError("len(z_levels_km) must equal nz")
    z_line = ",".join(f"{float(v):.6f}" for v in geometry.z_levels_km)

    with out.open("w", encoding="utf-8") as f:
        f.write("# extended AT3D grid data\n")
        if extra_metadata:
            for k, v in extra_metadata.items():
                f.write(f"# {k}: {v}\n")
        f.write(f"{geometry.nx},{geometry.ny},{geometry.nz}\n")
        f.write(f"{geometry.dx_km:.6f},{geometry.dy_km:.6f}\n")
        f.write(f"{z_line}\n")
        df.to_csv(f, index=False)

    return out


def build_from_retrieval_1d_netcdf(
    nc_path: str | Path,
    z_levels_km: Sequence[float],
    dx_km: Optional[float] = None,
    dy_km: Optional[float] = None,
    mode_count: int = 2,
    lat_var: str = "latitude",
    lon_var: str = "longitude",
    cv_var: str = "Cv_total",
    fine_fraction_var: str = "FineModeFraction",
    reff_vars: Optional[Sequence[str]] = None,
    veff_vars: Optional[Sequence[str]] = None,
    mr_vars: Optional[Sequence[str]] = None,
    mi_vars: Optional[Sequence[str]] = None,
    default_veff: float = 0.10,
    fallback_lat0: Optional[float] = 35.0,
    fallback_lon0: Optional[float] = -112.0,
    wavelength_index: int = 0,
    vertical_distribution: str = "from_nc",
    hmean_var: str = "Hmean_aerosol",
    sigma_var: str = "Saerosol",
    fixed_h_km: float = 2.0,
    fixed_sigma_km: float = 0.5,
    particle_density_g_cm3: float = 1.6,
    convert_lognormal_params: bool = True,
    a0_surf_var: str = "a0_surf",
    k0_surf_var: str = "k0_surf",
    b0_surf_var: str = "b0_surf",
    e0_surface_var: str = "e0_surface",
    wind_vv_var: str = "wind_vv",
    wind_wd_var: str = "wind_wd",
    surface_model: str = "diner",
) -> Tuple[pd.DataFrame, GridGeometry, ExtendedGridOptions]:
    """Convert a retrieval-1D netCDF (2D fields) into extended 3D grid dataframe.

    By default this uses common variable names from your 1DRT export. Missing fields
    are filled with conservative defaults so the pipeline can still run.
    """
    ds = xr.open_dataset(nc_path)

    cv2d = np.asarray(ds[cv_var].values, dtype=float)
    ny, nx = cv2d.shape
    nz = len(z_levels_km)

    if reff_vars is None:
        reff_vars = ["R_g_1", "R_g_2"][:mode_count]
    if veff_vars is None:
        veff_vars = ["Sigma_g_1", "Sigma_g_2"][:mode_count]
    if mr_vars is None:
        mr_vars = ["Refractive_Index_Real_Mode_1", "Refractive_Index_Real_Mode_2"][:mode_count]
    if mi_vars is None:
        mi_vars = ["Refractive_Index_Imaginary_Mode_1", "Refractive_Index_Imaginary_Mode_2"][:mode_count]

    # lat/lon: prefer file (supports 2D or spectral-like 3D), else regular-grid fallback
    lat_name = _first_existing_var(ds, [lat_var, 'lat', 'Latitude', 'LAT'])
    lon_name = _first_existing_var(ds, [lon_var, 'lon', 'Longitude', 'LON'])
    if lat_name is not None and lon_name is not None:
        lat2d = _to_2d_field(ds[lat_name].values, ny, nx, lat_name, wavelength_index)
        lon2d = _to_2d_field(ds[lon_name].values, ny, nx, lon_name, wavelength_index)
        invalid_geo = (
            (~np.isfinite(lat2d))
            | (~np.isfinite(lon2d))
            | (np.abs(lat2d) < 1e-12)
            | (np.abs(lon2d) < 1e-12)
            | (np.abs(lat2d) > 90.0)
            | (np.abs(lon2d) > 180.0)
        )
        lat2d = lat2d.astype(float)
        lon2d = lon2d.astype(float)
        lat2d[invalid_geo] = np.nan
        lon2d[invalid_geo] = np.nan
        if np.all(~np.isfinite(lat2d)) or np.all(~np.isfinite(lon2d)):
            dx_seed = 0.25 if dx_km is None else float(dx_km)
            dy_seed = 0.25 if dy_km is None else float(dy_km)
            lat2d, lon2d = generate_latlon(float(fallback_lat0), float(fallback_lon0), dx_seed * 1000.0, dy_seed * 1000.0, ny, nx)
    elif fallback_lat0 is not None and fallback_lon0 is not None:
        # If dx/dy are unknown, use a conservative fallback before synthetic lat/lon generation.
        dx_seed = 0.25 if dx_km is None else float(dx_km)
        dy_seed = 0.25 if dy_km is None else float(dy_km)
        lat2d, lon2d = generate_latlon(float(fallback_lat0), float(fallback_lon0), dx_seed * 1000.0, dy_seed * 1000.0, ny, nx)
    else:
        raise ValueError("lat/lon variables not found and fallback_lat0/lon0 are None")

    if dx_km is None or dy_km is None:
        dx_est, dy_est = _estimate_dxdy_from_latlon(lat2d, lon2d)
        dx_km = dx_est if dx_km is None else dx_km
        dy_km = dy_est if dy_km is None else dy_km

    # Ensure SHDOM x-axis (North) increases northward.
    dlat_row = np.nanmedian(lat2d[1:, :] - lat2d[:-1, :]) if lat2d.shape[0] > 1 else 0.0
    flip_north_axis = np.isfinite(dlat_row) and (dlat_row < 0)

    def _flip_north(a2d: np.ndarray) -> np.ndarray:
        return np.flipud(a2d) if flip_north_axis else a2d

    cv2d = _flip_north(cv2d)
    lat2d = _flip_north(lat2d)
    lon2d = _flip_north(lon2d)

    # Build vertical density profile from column-integrated Cv_total.
    vd_mode = str(vertical_distribution).lower()
    if vd_mode == 'from_nc' and (hmean_var in ds) and (sigma_var in ds):
        h2d = _flip_north(_to_2d_field(ds[hmean_var].values, ny, nx, hmean_var, wavelength_index))
        s2d = _flip_north(_to_2d_field(ds[sigma_var].values, ny, nx, sigma_var, wavelength_index))
    elif vd_mode in ('fixed', 'from_nc'):
        h2d = _flip_north(np.full((ny, nx), float(fixed_h_km), dtype=float))
        s2d = _flip_north(np.full((ny, nx), float(fixed_sigma_km), dtype=float))
    elif vd_mode == 'uniform':
        # Fallback legacy behavior (not recommended for Cv_total)
        dz_km = _z_layer_thickness_km(z_levels_km)
        cv3d = np.repeat((cv2d / np.sum(dz_km))[:, :, None], nz, axis=2)
        h2d = _flip_north(np.full((ny, nx), float(fixed_h_km), dtype=float))
        s2d = _flip_north(np.full((ny, nx), float(fixed_sigma_km), dtype=float))
    else:
        raise ValueError("vertical_distribution should be one of: from_nc, fixed, uniform")

    if vd_mode != 'uniform':
        cv3d = _column_to_mass_density_profile(
            cv_column_um=cv2d,
            z_levels_km=z_levels_km,
            h_km=h2d,
            sigma_km=s2d,
            particle_density_g_cm3=particle_density_g_cm3,
        )

    lat3d = _broadcast_2d_to_3d(lat2d, nz)
    lon3d = _broadcast_2d_to_3d(lon2d, nz)

    mode_fraction_2d: List[np.ndarray] = []
    if mode_count == 1:
        mode_fraction_2d = [np.ones_like(cv2d)]
    else:
        fine = (
            _flip_north(_to_2d_field(ds[fine_fraction_var].values, ny, nx, fine_fraction_var, wavelength_index))
            if fine_fraction_var in ds
            else np.full_like(cv2d, 0.5)
        )
        fine = np.clip(fine, 0.0, 1.0)
        mode_fraction_2d.append(fine)
        if mode_count >= 2:
            mode_fraction_2d.append(1.0 - fine)
        for _ in range(3, mode_count + 1):
            mode_fraction_2d.append(np.zeros_like(cv2d))

    base: Dict[str, np.ndarray] = {}
    # NC grid is ENU-like (rows~North, cols~East). AT3D expects NEU with x=North, y=East.
    Xn, Ye, Z = np.meshgrid(np.arange(ny), np.arange(nx), np.arange(nz), indexing="ij")
    base["x"] = Xn.reshape(-1)
    base["y"] = Ye.reshape(-1)
    base["z"] = Z.reshape(-1)
    base["cv"] = _flatten_xyz(cv3d)
    # Mode1 remains the canonical per-mode definition; scalar reff/veff are omitted to avoid duplicates.
    mode1_rm2d = _flip_north(_to_2d_field(ds[reff_vars[0]].values, ny, nx, reff_vars[0], wavelength_index)) if reff_vars and reff_vars[0] in ds else np.full_like(cv2d, 0.2)
    mode1_sig2d = _flip_north(_to_2d_field(ds[veff_vars[0]].values, ny, nx, veff_vars[0], wavelength_index)) if veff_vars and veff_vars[0] in ds else np.full_like(cv2d, default_veff)
    if convert_lognormal_params:
        mode1_reff2d = mode1_rm2d * np.exp(2.5 * mode1_sig2d**2)
        mode1_veff2d = np.exp(mode1_sig2d**2) - 1.0
    else:
        mode1_reff2d = mode1_rm2d
        mode1_veff2d = mode1_sig2d
    base["lat"] = _flatten_xyz(lat3d)
    base["lon"] = _flatten_xyz(lon3d)

    for i_mode in range(mode_count):
        m = i_mode + 1
        frac2d = mode_fraction_2d[i_mode]
        rm2d = _flip_north(_to_2d_field(ds[reff_vars[i_mode]].values, ny, nx, reff_vars[i_mode], wavelength_index)) if i_mode < len(reff_vars) and reff_vars[i_mode] in ds else mode1_rm2d
        sig2d = _flip_north(_to_2d_field(ds[veff_vars[i_mode]].values, ny, nx, veff_vars[i_mode], wavelength_index)) if i_mode < len(veff_vars) and veff_vars[i_mode] in ds else mode1_sig2d
        if convert_lognormal_params:
            reff2d = rm2d * np.exp(2.5 * sig2d**2)
            veff2d = np.exp(sig2d**2) - 1.0
        else:
            reff2d = rm2d
            veff2d = sig2d
        mr2d = _flip_north(_to_2d_field(ds[mr_vars[i_mode]].values, ny, nx, mr_vars[i_mode], wavelength_index)) if i_mode < len(mr_vars) and mr_vars[i_mode] in ds else np.full_like(cv2d, np.nan)
        mi2d = _flip_north(_to_2d_field(ds[mi_vars[i_mode]].values, ny, nx, mi_vars[i_mode], wavelength_index)) if i_mode < len(mi_vars) and mi_vars[i_mode] in ds else np.full_like(cv2d, np.nan)

        base[f"mode{m}_fraction"] = _flatten_xyz(_broadcast_2d_to_3d(frac2d, nz))
        base[f"mode{m}_reff"] = _flatten_xyz(_broadcast_2d_to_3d(reff2d, nz))
        base[f"mode{m}_veff"] = _flatten_xyz(_broadcast_2d_to_3d(veff2d, nz))
        base[f"mode{m}_mr"] = _flatten_xyz(_broadcast_2d_to_3d(mr2d, nz))
        base[f"mode{m}_mi"] = _flatten_xyz(_broadcast_2d_to_3d(mi2d, nz))

    # Optional surface BRDF/BPDF parameters from retrieval nc.
    # NOTE: user-provided kernels are closest to an RPV-like BRDF with hotspot;
    # at3d currently exposes `diner` (modified RPV + hotspot-like term), so we
    # store these fields and let simulation map them to the selected model.
    def _surface_field_or_nan(var_name: str, is_spectral: bool) -> np.ndarray:
        if var_name in ds:
            arr2d = _to_2d_field(ds[var_name].values, ny, nx, var_name, wavelength_index if is_spectral else 0)
            arr2d = _flip_north(arr2d)
        else:
            arr2d = np.full((ny, nx), np.nan, dtype=float)
        return _flatten_xyz(_broadcast_2d_to_3d(arr2d, nz))

    base["a0_surf"] = _surface_field_or_nan(a0_surf_var, is_spectral=True)
    base["k0_surf"] = _surface_field_or_nan(k0_surf_var, is_spectral=True)
    base["b0_surf"] = _surface_field_or_nan(b0_surf_var, is_spectral=True)
    base["e0_surface"] = _surface_field_or_nan(e0_surface_var, is_spectral=True)
    base["wind_vv"] = _surface_field_or_nan(wind_vv_var, is_spectral=False)
    base["wind_wd"] = _surface_field_or_nan(wind_wd_var, is_spectral=False)

    options = ExtendedGridOptions(mode_count=mode_count, include_surface=True, include_per_grid_refractive_index=True)
    df = build_extended_grid_dataframe(base, options)
    geom = GridGeometry(nx=ny, ny=nx, nz=nz, dx_km=float(dx_km), dy_km=float(dy_km), z_levels_km=list(z_levels_km))
    return df, geom, options


def build_from_les_arrays(
    qvapor_zyx: np.ndarray,
    z_levels_m: np.ndarray,
    lat_2d: np.ndarray,
    lon_2d: np.ndarray,
    dx_m: float,
    dy_m: float,
    coarse: Tuple[int, int, int] = (2, 4, 4),
    rho_air_kgm3: float = 1.0,
    default_reff: float = 12.0,
    default_veff: float = 0.10,
) -> Tuple[pd.DataFrame, GridGeometry, ExtendedGridOptions]:
    """Build extended dataframe from LES-like arrays (compatible with your WRF workflow)."""
    cz, cy, cx = coarse
    qv_c = _coarse_mean_3d(qvapor_zyx, cz, cy, cx)
    lat_c = _coarse_mean_2d(lat_2d, cy, cx)
    lon_c = _coarse_mean_2d(lon_2d, cy, cx)
    z_c = np.asarray(z_levels_m[: (len(z_levels_m) // cz) * cz], dtype=float).reshape(-1, cz).mean(axis=1)

    lwc_gm3 = qv_c * rho_air_kgm3 * 1000.0
    nz, ny, nx = lwc_gm3.shape
    lwc_yxz = np.transpose(lwc_gm3, (1, 2, 0))

    # LES arrays are typically indexed [z, north, east]; map to AT3D NEU (x=north, y=east).
    Xn, Ye, Z = np.meshgrid(np.arange(ny), np.arange(nx), np.arange(nz), indexing="ij")
    base: Dict[str, np.ndarray] = {
        "x": Xn.reshape(-1),
        "y": Ye.reshape(-1),
        "z": Z.reshape(-1),
        "cv": _flatten_xyz(lwc_yxz),
        "lat": _flatten_xyz(_broadcast_2d_to_3d(lat_c, nz)),
        "lon": _flatten_xyz(_broadcast_2d_to_3d(lon_c, nz)),
        "mode1_fraction": np.ones(nx * ny * nz),
        "mode1_reff": _flatten_xyz(np.full_like(lwc_yxz, default_reff, dtype=float)),
        "mode1_veff": _flatten_xyz(np.full_like(lwc_yxz, default_veff, dtype=float)),
        "mode1_mr": np.full(nx * ny * nz, np.nan),
        "mode1_mi": np.full(nx * ny * nz, np.nan),
    }
    options = ExtendedGridOptions(mode_count=1, include_surface=True, include_per_grid_refractive_index=False)
    df = build_extended_grid_dataframe(base, options)
    geom = GridGeometry(
        nx=ny,
        ny=nx,
        nz=nz,
        dx_km=(dy_m * cy) / 1000.0,
        dy_km=(dx_m * cx) / 1000.0,
        z_levels_km=(z_c / 1000.0).tolist(),
    )
    return df, geom, options



def parse_z_levels(z: str) -> List[float]:
    """Accept "0.01:0.5:20" or "0.01,0.51,1.01"."""
    if ":" in z:
        a, b, c = [float(v) for v in z.split(":")]
        return list(np.arange(a, c + 1e-12, b))
    return [float(v) for v in z.split(",") if v.strip()]


def run_retrieval_case(
    input_nc: str,
    output_csv: str,
    z_levels_km: Sequence[float],
    dx_km: Optional[float] = None,
    dy_km: Optional[float] = None,
    mode_count: int = 2,
    wavelength_index: int = 0,
    fallback_lat0: float = 35.0,
    fallback_lon0: float = -112.0,
    vertical_distribution: str = "from_nc",
    fixed_h_km: float = 2.0,
    fixed_sigma_km: float = 0.5,
    particle_density_g_cm3: float = 1.6,
) -> Path:
    """Spyder-friendly wrapper: one function call to build CSV from retrieval nc."""
    df, geom, options = build_from_retrieval_1d_netcdf(
        nc_path=input_nc,
        z_levels_km=z_levels_km,
        dx_km=dx_km,
        dy_km=dy_km,
        mode_count=mode_count,
        wavelength_index=wavelength_index,
        fallback_lat0=fallback_lat0,
        fallback_lon0=fallback_lon0,
        vertical_distribution=vertical_distribution,
        fixed_h_km=fixed_h_km,
        fixed_sigma_km=fixed_sigma_km,
        particle_density_g_cm3=particle_density_g_cm3,
    )
    return write_extended_grid_csv(output_csv, df, geom, options)


if __name__ == "__main__":
    # =========================
    # Spyder editable run block
    # =========================
    # 直接修改下面变量后，在 Spyder 中 Run File 即可。
    input_nc = "../data/retrieval_1d/2019_0806_1839_N_Pxl25_3_3.nc"
    output_csv = "../data/synthetic_cloud_fields/jpl_les/retrieval_2019_0806_1839_extended.csv"
    dx_km = None  # None -> estimate from lat/lon in nc
    dy_km = None  # None -> estimate from lat/lon in nc
    z_levels_km = parse_z_levels("0.01:0.5:20")
    mode_count = 2
    wavelength_index = 0  # 例如 AirMSPI: 0..6 -> [355,380,445,470,555,660,865]
    fallback_lat0 = 35.0
    fallback_lon0 = -112.0
    vertical_distribution = "from_nc"  # from_nc | fixed | uniform
    fixed_h_km = 2.0
    fixed_sigma_km = 0.5
    particle_density_g_cm3 = 1.6

    out = run_retrieval_case(
        input_nc=input_nc,
        output_csv=output_csv,
        dx_km=dx_km,
        dy_km=dy_km,
        z_levels_km=z_levels_km,
        mode_count=mode_count,
        wavelength_index=wavelength_index,
        fallback_lat0=fallback_lat0,
        fallback_lon0=fallback_lon0,
        vertical_distribution=vertical_distribution,
        fixed_h_km=fixed_h_km,
        fixed_sigma_km=fixed_sigma_km,
        particle_density_g_cm3=particle_density_g_cm3,
    )
    print(f"✅ wrote: {out}")
